management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: news-aggregator-demo
    description: News aggregator about The Spring Framework.
    author: Denys Kushchev
    version: '@project.version@'
spring:
  profiles:
    active: prod